apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-aggregate
  namespace: megastack-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-aggregate
  namespace: megastack-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-aggregate
  template:
    metadata:
      labels:
        app: log-aggregate
    spec:
      serviceAccountName: log-aggregate
      containers:
        - name: log-aggregate
          image: quay.io/rh-ee-nmendels/rmw-log-aggregate
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
          resources:
            requests:
              cpu: 1000m
              memory: 4Gi
            limits:
              cpu: 1000m
              memory: 4Gi
          env:
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  containerName: log-aggregate
---
apiVersion: v1
kind: Service
metadata:
  name: log-aggregate
  namespace: megastack-application
spec:
  selector:
    app: log-aggregate
  ports:
    - name: http  
      port: 8080
      targetPort: http
  type: ClusterIP  
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: log-aggregate
  namespace: megastack-application
spec:
  to:
    kind: Service
    name: log-aggregate
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
