apiVersion: v1
kind: ServiceAccount
metadata:
  name: eggclicker
  namespace: byteme-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eggclicker
  namespace: byteme-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eggclicker
  template:
    metadata:
      labels:
        app: eggclicker
    spec:
      serviceAccountName: eggclicker
      containers:
        - name: eggclicker
          image: quay.io/rh-ee-nmendels/rmw-egg-clicker
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eggclicker
  namespace: byteme-application
spec:
  selector:
    app: eggclicker
  ports:
    - name: http  
      port: 8080
      targetPort: http
  type: ClusterIP  
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: eggclicker
  namespace: byteme-application
spec:
  to:
    kind: Service
    name: eggclicker
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
