apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizonhopper
  namespace: scalesurfers-horizonhopper
  labels:
    app: horizonhopper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: horizonhopper
  template:
    metadata:
      labels:
        app: horizonhopper
    spec:
      containers:
        - name: horizonhopper
          image: "colinianking/stress-ng:ca4c54389728d7abe5162d93a831a72427890f83"
          command: 
          - "/bin/sh"
          - "-c"
          - "stress-ng --temp-path /tmp --vm 1 --vm-bytes 200M"
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 100m
              memory: 250Mi