{
 "title": "Kubernetes Resource Recommendation",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "query_result(sum(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\",workload_type!=\"job\"} @ end()) by (workload))"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(sum(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\",workload=\"$workload\",workload_type!=\"job\"} @ end()) by (pod))"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "query_result(sum(kube_pod_container_info{namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (container))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$workload :: $container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "container",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Recommendation",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod)))",
       "legendFormat": "Maximum CPU usage"
      },
      {
       "expr": "max(quantile_over_time(0.95, (sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod)))[$__range:$__rate_interval]))",
       "legendFormat": "cpu recommendation"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\",pod=~\"$pod\",container=~\"$container\"}) by (container)",
       "legendFormat": "cpu request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\",pod=~\"$pod\",container=~\"$container\"}) by (container)",
       "legendFormat": "cpu cpu limit"
      }
     ]
    },
    {
     "title": "Memory Recommendation",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod))) by (container)",
       "legendFormat": "Maximum Usage"
      },
      {
       "expr": "1.15 * max(max_over_time(((sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod) ))[$__range:$__rate_interval]))) by (container)",
       "legendFormat": "Recommendation"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",pod=~\"$pod\",container=~\"$container\"}) by (container)",
       "legendFormat": "Requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$pod\",container=~\"$container\"}) by (container)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "CPU usage by pod",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod))",
       "legendFormat": "{{pod}} :: Usage"
      },
      {
       "expr": "quantile_over_time(0.95, (sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod)))[$__range:$__rate_interval])",
       "legendFormat": "{{pod}} :: Recommendation"
      }
     ]
    },
    {
     "title": "Memory usage by pod",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod))",
       "legendFormat": "{{pod}} :: Usage"
      },
      {
       "expr": "1.15 * max_over_time(((sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod) ))[$__range:$__rate_interval]))",
       "legendFormat": "{{pod}} :: Recommendation"
      }
     ]
    },
    {
     "title": "Max CPU usage & Recommendation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod)))",
       "legendFormat": "Maximum Usage"
      },
      {
       "expr": "max(quantile_over_time(0.95, (sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod)))[$__range:$__rate_interval]))",
       "legendFormat": "Recommendation"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\",pod=~\"$pod\",container=~\"$container\"}) by (container)",
       "legendFormat": "Requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\",pod=~\"$pod\",container=~\"$container\"}) by (container)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Max Memory usage & Recommendation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod))) by (container)",
       "legendFormat": "Maximum Usage"
      },
      {
       "expr": "1.15 * max(max_over_time(((sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$pod\", container=~\"$container\"}) by (namespace,pod,container) * on (namespace,pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",namespace=\"$namespace\",pod=~\"$pod\"} @ end()) by (namespace,pod) ))[$__range:$__rate_interval]))) by (container)",
       "legendFormat": "Recommendation"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",pod=~\"$pod\",container=~\"$container\"}) by (container)",
       "legendFormat": "Requests"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\",pod=~\"$pod\",container=~\"$container\"}) by (container)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "CPU Throttled seconds by pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\", image!=\"\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (container,pod) > 0",
       "legendFormat": "{{ pod }} :: {{ container }}"
      }
     ]
    },
    {
     "title": "OOM Events by namespace, pod",
     "type": "timeseries",
     "description": "No data is generally a good thing here.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(container_oom_events_total{namespace=~\"$namespace\",pod=~\"pod\",container=~\"$container\"}[$__rate_interval])) by (container, pod) > 0",
       "legendFormat": "OOM Events"
      }
     ]
    }
   ]
  }
 ]
}