apiVersion: apps/v1
kind: Deployment
metadata:
  name: silentrunner
  namespace: scalesurfers-silentrunner
  labels:
    app: silentrunner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: silentrunner
  template:
    metadata:
      labels:
        app: silentrunner
    spec:
      containers:
        - name: silentrunner
          image: "colinianking/stress-ng:ca4c54389728d7abe5162d93a831a72427890f83"
          command: 
          - "/bin/sh"
          - "-c"
          - "stress-ng --temp-path /tmp --vm 1 --vm-bytes 200M"
