apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudchaser
  namespace: scalesurfers-cloudchaser
  labels:
    app: cloudchaser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudchaser
  template:
    metadata:
      labels:
        app: cloudchaser
    spec:
      containers:
        - name: cloudchaser
          image: "colinianking/stress-ng:ca4c54389728d7abe5162d93a831a72427890f83"
          command:
          - "/bin/sh"
          - "-c"
          - "stress-ng --temp-path /tmp --vm 1 --vm-bytes 200M"
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 100m
              memory: 250Mi
