apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerohero
  namespace: scalesurfers-zerohero
  labels:
    app: zerohero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zerohero
  template:
    metadata:
      labels:
        app: zerohero
    spec:
      containers:
        - name: zerohero
          image: "colinianking/stress-ng:ca4c54389728d7abe5162d93a831a72427890f83"
          command: 
          - "/bin/sh"
          - "-c"
          - "stress-ng --temp-path /tmp --vm 1 --vm-bytes 200M"
