apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: primefactors
  namespace: hyperburst-application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: primefactors
  minReplicas: 2
  maxReplicas: # Replace with the maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: # Replace with the desired CPU utilization percentage